language: ruby
rvm:
- 2.1.1
- 2.0.0
- jruby
- rbx
matrix:
  allow_failures:
  # no keyword argument support in rbx
- rbx
env:
  global:
  - TRAVIS=1
  - secure: Clln+r2rG6adnmVjS0zGMVHs1hOq58UPIqRE73xW3MPLOdozGUyIZ0RrAU2new1h4sqk/5HVwG5NSW7AsUJDGgkNCDx4saJbf/G+oKIity1zNxlHZu5ijZOZGyxYNzGGM4cb2OO6RS6lfzA6TFv2TQtw8DDfKjzG2gpuJOje8sU=
